### ISSUE TITLE
Version in repository is unpublished

### ISSUE THREAD

**Issue by tony37** [sugarlabs/across-and-down-activity#14]
Current version in ASLO is 24 dated October 29, 2011. 
Version here is still 24 despite the documented chantes.
Since these chantes have not been published, a simple increment to 25 may be sufficient, 
appropriately tagged and published to ASLO.

**Comment by quozl** [comment]
+1.  @pro-panda, @pipix51, @yashagrawal3, @vipulgupta2048, @chimosky, @Aniket21mathur; thanks for your work since v24, but your commits are wasted without someone willing to maintain this activity by making a release.  See [activity maintainer checklist](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#checklist---maintainer) for what needs doing.

**Comment by Aniket21mathur** [comment]
@quozl I am willing to make a release of this activity.Thanks!

**Comment by quozl** [comment]
Thanks.  Any questions about the checklist, ask on sugar-devel@ mailing list.

**Comment by quozl** [comment]
v25 is tagged, release to activities.sugarlabs.org is next action for @Aniket21mathur.

**Comment by Aniket21mathur** [comment]
Before release I have a query -
The .xo is compatible with sugar 0.112 for sure, what is the oldest version of sugar that will support the new version of the activity?

**Comment by quozl** [comment]
I usually say 0.98 to 0.112, unless I know of some new API being used.  From memory because 0.98 is roughly when GTK3 support became available.  But I've not recently checked this.  It should be easy to do; look in the Sugar repository by tag and see when it was ported from GTK2 to GTK3.

**Comment by Aniket21mathur** [comment]
Thanks @quozl .
New version uploaded to sandbox for review!

**Comment by quozl** [comment]
Reviewed, pushed.
